### PR TITLE
Fixed looping in register

### PR DESCRIPTION
**Pull request by hunter-holton**
The looping error that we had in the register button is fixed it only adds the test name once then prints once as well

### CODE REVIEW

**Review by chuizar — APPROVED** [review]
Looks good, fixes the problem with the loop

**Review by Esmael377 — COMMENTED** [review]
esmael@esmael-VirtualBox:~/Desktop/GPspring2021/GPspring2021$ javac GroupProject.java
GroupProject.java:140: error: 'else' without 'if'
else {
^
GroupProject.java:158: error: invalid method declaration; return type required
    public UserEmail(){
           ^
GroupProject.java:197: error: illegal start of expression
	public class HandleActionEventsForJButton extends JFrame implements ActionListener {
	^
GroupProject.java:239: error: class, interface, or enum expected
}
^
4 errors

**Comment by Esmael377** [comment]
I see those errors , if you want to check it out.

**Comment by hunter-holton** [comment]
> esmael@esmael-VirtualBox:~/Desktop/GPspring2021/GPspring2021$ javac GroupProject.java
> GroupProject.java:140: error: 'else' without 'if'
> else {
> ^
> GroupProject.java:158: error: invalid method declaration; return type required
> public UserEmail(){
> ^
> GroupProject.java:197: error: illegal start of expression
> public class HandleActionEventsForJButton extends JFrame implements ActionListener {
> ^
> GroupProject.java:239: error: class, interface, or enum expected
> }
> ^
> 4 errors

it looks like you havent updated your code since we pushed stuff our group project code is only 96 lines i dont see how you haven 239 lines the code works on mine machine so make sure you have the class updated before running if you could look at them again after you update the class that would be great thanks!

**Comment by Esmael377** [comment]
> > esmael@esmael-VirtualBox:~/Desktop/GPspring2021/GPspring2021$ javac GroupProject.java
> > GroupProject.java:140: error: 'else' without 'if'
> > else {
> > ^
> > GroupProject.java:158: error: invalid method declaration; return type required
> > public UserEmail(){
> > ^
> > GroupProject.java:197: error: illegal start of expression
> > public class HandleActionEventsForJButton extends JFrame implements ActionListener {
> > ^
> > GroupProject.java:239: error: class, interface, or enum expected
> > }
> > ^
> > 4 errors
> 
> it looks like you havent updated your code since we pushed stuff our group project code is only 96 lines i dont see how you haven 239 lines the code works on mine machine so make sure you have the class updated before running if you could look at them again after you update the class that would be great thanks!

if you see the last error messages at 239 lines, That telling us it is updated.

**Comment by hunter-holton** [comment]
> > > esmael@esmael-VirtualBox:~/Desktop/GPspring2021/GPspring2021$ javac GroupProject.java
> 
> > > GroupProject.java:140: error: 'else' without 'if'
> 
> > > else {
> 
> > > ^
> 
> > > GroupProject.java:158: error: invalid method declaration; return type required
> 
> > > public UserEmail(){
> 
> > > ^
> 
> > > GroupProject.java:197: error: illegal start of expression
> 
> > > public class HandleActionEventsForJButton extends JFrame implements ActionListener {
> 
> > > ^
> 
> > > GroupProject.java:239: error: class, interface, or enum expected
> 
> > > }
> 
> > > ^
> 
> > > 4 errors
> 
> > 
> 
> > it looks like you havent updated your code since we pushed stuff our group project code is only 96 lines i dont see how you haven 239 lines the code works on mine machine so make sure you have the class updated before running if you could look at them again after you update the class that would be great thanks!
> 
> 
> 
> if you see the last error messages at 239 lines, That telling us it is updated. 

How long is your code it should me 93 lines if I'm reading this correctly it's 239 there are not that many lines in group project you need to update the code your looking at to make sure it is current I have ran multiple times and have no issues.

**Comment by Esmael377** [comment]
I am confirming to merge.

**Comment by Esmael377** [comment]
merge cofirmed .

**Review by Esmael377 — APPROVED** [review]

**Pull request merged**
